import json
import cProfile
import pstats
import io
import sugarscape

# Minimal set of defaults needed to init Sugarscape without the full run_experiments setup
conf = json.load(open('configs/test_homo_fvdm_selfish.json'))

defaults = {
    "agentAggressionFactor": [0, 0],
    "agentBaseInterestRate": [0, 0],
    "agentDecisionModel": "egoist",
    "agentDecisionModelFactor": [1.0, 1.0],
    "agentDecisionModelLookaheadDiscount": [0, 0],
    "agentDecisionModelLookaheadFactor": [0, 0],
    "agentDecisionModels": ["egoist"],
    "agentDecisionModelTribalFactor": [0, 0],
    "agentDepressionPercentage": 0,
    "agentLogfile": None,
    "agentDiseaseProtectionChance": [0, 0],
    "agentDynamicSelfishnessFactor": [0, 0],
    "agentDynamicTemperanceFactor": [0, 0],
    "agentFemaleFertilityAge": [12, 15],
    "agentFemaleInfertilityAge": [40, 50],
    "agentFertilityFactor": [1, 1],
    "agentImmuneSystemLength": 11,
    "agentInheritancePolicy": "children",
    "agentLeader": False,
    "agentLendingFactor": [0, 0],
    "agentLoanDuration": [0, 0],
    "agentLookaheadFactor": [0, 0],
    "agentMaleFertilityAge": [12, 15],
    "agentMaleInfertilityAge": [40, 50],
    "agentMaleToFemaleRatio": 1.0,
    "agentMaxAge": [60, 100],
    "agentMaxFriends": [0, 0],
    "agentMovement": [1, 1],
    "agentMovementMode": "cardinal",
    "agentReplacements": 0,
    "agentSelfishnessFactor": [0, 0],
    "agentSpiceMetabolism": [1, 1],
    "agentStartingSpice": [10, 40],
    "agentStartingSugar": [10, 40],
    "agentSugarMetabolism": [1, 1],
    "agentTagging": False,
    "agentTagPreferences": [0, 0],
    "agentTagStringLength": 11,
    "agentTemperanceFactor": [0, 0],
    "agentTradeFactor": [0, 0],
    "agentUniversalSpice": [0, 0],
    "agentUniversalSugar": [0, 0],
    "agentVision": [1, 1],
    "agentVisionMode": "cardinal",
    "aggressionFactor": 0,
    "baseInterestRate": 0,
    "debugMode": ["none"],
    "decisionModel": "egoist",
    "decisionModelFactor": 1.0,
    "decisionModelLookaheadDiscount": 0,
    "decisionModelLookaheadFactor": 0,
    "decisionModelTribalFactor": 0,
    "depressionFactor": 0,
    "diseaseAggressionPenalty": [0, 0],
    "diseaseFertilityPenalty": [0, 0],
    "diseaseFriendlinessPenalty": [0, 0],
    "diseaseHappinessPenalty": [0, 0],
    "diseaseIncubationPeriod": [0, 0],
    "diseaseList": [],
    "diseaseMovementPenalty": [0, 0],
    "diseaseProtectionChance": 0,
    "diseaseSpiceMetabolismPenalty": [0, 0],
    "diseaseSugarMetabolismPenalty": [0, 0],
    "diseaseTagStringLength": [0, 0],
    "diseaseTimeframe": [0, 0],
    "diseaseTransmissionChance": [0, 0],
    "diseaseVisionPenalty": [0, 0],
    "dynamicSelfishnessFactor": 0,
    "dynamicTemperanceFactor": 0,
    "environmentEquator": -1,
    "environmentFile": None,
    "environmentHeight": 50,
    "environmentMaxCombatLoot": 1,
    "environmentMaxSpice": 4,
    "environmentMaxSugar": 4,
    "environmentMaxTribes": 1,
    "environmentPollutionDiffusionDelay": 0,
    "environmentPollutionDiffusionTimeframe": [0, 0],
    "environmentPollutionTimeframe": [0, 0],
    "environmentQuadrantSizeFactor": 1.0,
    "environmentSeasonalGrowbackDelay": 0,
    "environmentSeasonInterval": 0,
    "environmentSpiceConsumptionPollutionFactor": 0,
    "environmentSpicePeaks": [[25, 25, 4, 1]],
    "environmentSpiceProductionPollutionFactor": 0,
    "environmentSpiceRegrowRate": 1,
    "environmentStartingQuadrants": [1, 2, 3, 4],
    "environmentSugarConsumptionPollutionFactor": 0,
    "environmentSugarPeaks": [[25, 25, 4, 1]],
    "environmentSugarProductionPollutionFactor": 0,
    "environmentSugarRegrowRate": 1,
    "environmentTribePerQuadrant": False,
    "environmentUniversalSpiceIncomeInterval": 0,
    "environmentUniversalSugarIncomeInterval": 0,
    "environmentWidth": 50,
    "environmentWraparound": True,
    "experimentalGroup": None,
    "fertilityAge": [12, 15],
    "fertilityFactor": [1, 1],
    "follower": False,
    "headlessMode": True,
    "immuneSystem": [1, 1],
    "infertilityAge": [40, 50],
    "inheritancePolicy": "children",
    "interfaceHeight": 1000,
    "interfaceWidth": 900,
    "keepAliveAtEnd": False,
    "keepAlivePostExtinction": False,
    "lendingFactor": 0,
    "loanDuration": 0,
    "logfile": None,
    "logfileFormat": "json",
    "lookaheadFactor": 0,
    "maxAge": [60, 100],
    "maxFriends": 0,
    "movement": 1,
    "movementMode": "cardinal",
    "neighborhoodMode": "vonNeumann",
    "profileMode": False,
    "screenshots": False,
    "seed": 42,
    "selfishnessFactor": 0,
    "sex": "any",
    "spice": [50, 100],
    "startingAgents": 250,
    "startingDiseases": 0,
    "startingDiseasesPerAgent": [0, 0],
    "sugar": [50, 100],
    "tagging": False,
    "tagPreferences": [0, 0],
    "tags": [0, 0],
    "temperanceFactor": 0,
    "timesteps": 200,
    "tradeFactor": 0,
    "universalSpice": 0,
    "universalSugar": 0,
    "vision": 1,
    "visionMode": "cardinal"
}

for k, v in defaults.items():
    if k not in conf:
        conf[k] = v

pr = cProfile.Profile()
pr.enable()

s = sugarscape.Sugarscape(conf)
s.updateRuntimeStats()
for t in range(conf['timesteps']):
    s.doTimestep()
    if len(s.agents) == 0 or s.end:
        break

pr.disable()

sio = io.StringIO()
ps = pstats.Stats(pr, stream=sio).sort_stats('cumulative')
ps.print_stats(30)
print(sio.getvalue())
